### ISSUE TITLE
Including a constant as a parameter default.

### ISSUE THREAD

**Issue by Kruithne** [textmate/php.tmbundle#75]
In the latest versions of PHP, it is perfectly valid to use a constant (`const`) as a default for a function parameter.

`public function __construct(int $flags = self::DEFAULT_FLAGS) {`

This however, is detected as a syntax error by php.tmbundle, as show below.

![kramework7autoloader php_at_master_ _kruithnekra_2017-01-26_21-47-49](https://cloud.githubusercontent.com/assets/682348/22351820/9847560a-e411-11e6-9b6a-a41f73763a72.png)

**Comment by stijnstijn** [comment]
The problem seems to be that [the relevant bit of the grammar](https://github.com/textmate/php.tmbundle/blob/4b5c247c34f6c73e193ec810f320acad8a61b263/Syntaxes/PHP.plist#L539) still plays by PHP 5.1 rules. That is, it allows arrays and class names as type declarations; and default values then need to be either `NULL` or a long-style array declaration if the type is `array`, short style being introduced in 5.4.

So the problem is wider than just not accepting constants; the grammar needs to be updated to accept the type declarations PHP versions later than 5.1 allow.

**Comment by infininight** [comment]
This has been corrected by 706c68037661378f964657d00b85c3c8bdb8bec7, also added was return-type matching.
